### ISSUE TITLE
Typo in Ch. 6

### ISSUE THREAD

**Issue by darribas** [gdsbook/book#121]
Shared by email:

> While going through your book, I noticed a small error on the following page:
>
> [https://geographicdata.science/book/notebooks/06_spatial_autocorrelation.html#id3](https://geographicdata.science/book/notebooks/06_spatial_autocorrelation.html#id3)
>
> The text under the plot_moran(moran) command says that - 'The black rug signals the mean', while the rug is blue in the diagram.

**Comment by jeffcsauer** [comment]
@darribas see #125 - just did the small fix. Only additional note is that it included my slightly different python version.
