### ISSUE TITLE
Ch. 1 - need to specify tag in docker `pull` 

### ISSUE THREAD

**Issue by e-chong** [gdsbook/book#122]
In the [`Run the book's container`](https://geographicdata.science/book/notebooks/01_geospatial_computational_environment.html#run-the-book-s-container) section, I would like to suggest that you change the following docker command:

```
docker pull gdsbook/stack
```

to:

```
docker pull gdsbook/stack:3.0
```

When I run the command that is currently in the book in Windows PowerShell, I receive the following error:

```
Error response from daemon: manifest for gdsbook/stack:latest not found: manifest unknown: manifest unknown
```

Per [this thread](https://forums.docker.com/t/docker-pull-manifest-not-found/78650) on the Docker forums, I understand that running the command _without_ the 3.0 tag defaults to pulling the image with `tag:latest`, but the "latest" tag doesn't exist, so I receive that error.

Thanks very much for all your work on this wonderful book!

**Comment by darribas** [comment]
Thank you very much for reporting this. We've updated the chapter in #174 and we're now pointing to a specific tag. In the process, we've also switched to the [`gds_env`](https://darribas.org/gds_enc) to streamline things and this is also reflected.
