### ISSUE TITLE
GDS Web build is reverting caption updates

### ISSUE THREAD

**Issue by sjsrey** [gdsbook/book#177]
![image](https://user-images.githubusercontent.com/118042/121407426-27408200-c914-11eb-9138-322f9f373ec9.png)

**Comment by darribas** [comment]
More background:

- Example of build that removes captions [[URL]](https://github.com/gdsbook/book/commit/c952b4da24f05a27bcaf1f78316f4b6b0f76ef50#diff-227f82e0a28e4fd163bc398ab0867cf9cfdf3ce8b0ed9d6962a6637d62f50afb)
- Original commit with changes [[URL]](https://github.com/gdsbook/book/commit/3d4bb1055552dc076e8666911f2aa126f9ba9c1f#diff-227f82e0a28e4fd163bc398ab0867cf9cfdf3ce8b0ed9d6962a6637d62f50afb)

**Comment by darribas** [comment]
Fixed on #178
