### ISSUE TITLE
Scrambled text in Choropleth chapter

### ISSUE THREAD

**Issue by darribas** [gdsbook/book#181]
From reader report:

> While in Chapter Choropleth Mapping underSection: Sequential Color Schemes ( https://geographicdata.science/book/notebooks/05_choropleth.html ): It looks like it needs to be recompiled, as some of the text scrambled like................. for file in /proc/*/status ; do awk ‘/VmSwap|Name/{printf 2""3}END{ print “”}’ $file; done | sort -k 2 -n -r | less### Diverging Color Schemes..................

This seems to be injected from the $\LaTeX$ build pipeline @sjsrey has on post processing?

**Comment by sjsrey** [comment]
I do't think this is from the pipeline as the generated files are never checked into the repository?
