### ISSUE TITLE
Add a makefile target to generate epub  

### ISSUE THREAD

**Issue by kidpixo** [gdsbook/book#223]
I started to play with this just copying the makefile html target and modifying the jupyter-book command to

```
jupyter-book build tmp_book --builder=custom --custom-builder=epub
```
this works in the cli, but the make command still fails with

```
The Table of Contents file is malformed: toc is not a mapping: <class 'list'>
You may need to migrate from the old format, using:
        jupyter-book toc migrate /book/tmp_book/_toc.yml -o /book/tmp_book/_toc.yml
```

I put this last line in the make target with no luck.

The other problem is that the generated epub toc contains only one item `Home`, I tried to play with the [Sphinx](https://www.sphinx-doc.org/en/1.4.9/config.html) option `epub_tocdepth` with no luck.

The makefile target `epub` ends up generating `epub/gdsbook.epub` and looks like this

```
epub: sync
	echo "Cleaning up existing tmp_book folder..."
	rm -rf docs
	rm -rf tmp_book
	echo "Populating build folder..."
	mkdir tmp_book
	mkdir tmp_book/notebooks
	cp notebooks/*.ipynb tmp_book/notebooks/
	cp notebooks/references.bib tmp_book/notebooks/
	cp -r data tmp_book/data
	cp -r figures tmp_book/figures
	cp -r infrastructure/website_content/* tmp_book/
	cp infrastructure/logo/ico_256x256.png tmp_book/logo.png
	cp infrastructure/logo/favicon.ico tmp_book/favicon.ico
	echo "Starting book build..."
	jupyter-book toc migrate /book/tmp_book/_toc.yml
	jupyter-book build tmp_book --builder=custom --custom-builder=epub
	echo "Moving build..."
	mkdir epub
	mv tmp_book/_build/epub/Python.epub epub/gdsbook.epub
	echo "Cleaning up..."
	rm -r tmp_book

```

**Comment by darribas** [comment]
Thank you very much @kidpixo for contributing to the book and providing code for this. We (@ljwolf and @sjsrey) considered adding it to the official repo and decided _not_ to as it could be seen as breaking our editorial contract with CRC Press. However, if you find it useful, we see no reason for you to use the code :-)

I'm closing the issue but, if something else of relevance crops up, please do feel free to reopen.
