### ISSUE TITLE
CHAPTER: Introduction & Epilogue

### ISSUE THREAD

**Issue by ljwolf** [gdsbook/book#252]
Introduction:
- acknowledgement/caveat emptor that the code will change in the future. 
- motivation for writing & concerns at the time of the book
  - why a book *on this stuff*
  - why does this book *avoid other stuff*
  - why a book *this way*

Epilogue:
- where to go for next steps and open areas of research.
- the book offers more than just guidance about packages
- style that we presented it provides ways to move forward that we do not directly document.

**Comment by darribas** [comment]
xref #155 for the prologue/introduction and #205 for reference.  I _think_ this supersedes, so will close those but we can always return.

**Comment by darribas** [comment]
Update: we've added the space to add the epilogue in the book with https://github.com/gdsbook/book/pull/260

**Comment by darribas** [comment]
After @ljwolf's pass merged in #270, this is good to go, so moving to `with-publisher`
