### ISSUE TITLE
Spatial Weights chapter - small typos

### ISSUE THREAD

**Issue by jo-wilkin** [gdsbook/book#266]
Used the Contiguity section on generating spatial weights for Californian counties dataset -all worked :). Quick scan over the remaining content, some small typos spotted:

- [x] "Spatial weightsoften" - needs a space!
- [x] # Build a regular 3x3 lattice and draw it here | wr = weights.contiguity.Rook.from_dataframe(gdf) - is this code comment intended? Doesn't really match what you'd interpret the code as doing per se...
- [x] # Build a regular 3x3 lattice and draw it here | wq = weights.contiguity.Queen.from_dataframe(gdf) - ibid.
- [x] Question 5.1. examine - missing capital. All other questions are capitalised.

**Comment by darribas** [comment]
Amazing! Thanks very much Jo! We'll get to those asap!
