### ISSUE TITLE
Geographic thinking for data scientists - Small typo

### ISSUE THREAD

**Issue by rnanclares** [gdsbook/book#267]
> And they draws this population from elsewhere.

Replace draws with draw

**Comment by spibe** [comment]
>  it becomes more important to extract meainingful insights from common geographical properties 

Replace meainingful with meaningful

**Comment by spibe** [comment]
> phenomenon at different points in, time we will need different arrays, possibly connected.

I would place the comma like this: phenomenon at different points in time, we will need different arrays, possibly connected.

**Comment by spibe** [comment]
> but also our analygical goal.

Replace analygical with analytical

**Comment by spibe** [comment]
> Thus, transparency, accessibility, and inclusivemenss are critical for good science.

Replace inclusivemenss with inclusiveness

**Comment by rnanclares** [comment]
The _"cost"_ of moving between data structures _have_ been lowered. 
Replace "cost" with "costs" or have with has

**Comment by spibe** [comment]
> results of computations o rbreak analytical workflows entirely.

Replace o rbreak with or break

**Comment by ljwolf** [comment]
closed by #280

**Comment by ljwolf** [comment]
Thanks!
