### ISSUE TITLE
Computational Tools for Geographic Data Science - Small typos

### ISSUE THREAD

**Issue by rnanclares** [gdsbook/book#268]
Opening this issue so you can easily find where the typos are located (by notebook).

**Comment by rnanclares** [comment]
> results of computations o rbreak analytical workflows entirely.

Replace o rbreak with or break

_Originally posted by @spibe in https://github.com/gdsbook/book/issues/267#issuecomment-1109567872_

**Comment by rnanclares** [comment]
> This counter may not always be visible i all of the __foramts__ a __notbook__ may be viewed.

Replaces foramts with formats and notbook with notebook

**Comment by ljwolf** [comment]
closed by #280

**Comment by ljwolf** [comment]
Thank you for filing these! Definitely let us know if there are any more 😄
