### ISSUE TITLE
`osmnx` version issues

### ISSUE THREAD

**Issue by darribas** [gdsbook/book#271]
I'm currently getting the following error in chapter 12 when trying to retrieve data from OSM:

![image](https://user-images.githubusercontent.com/417363/166557269-6dab1538-1367-40b9-9919-33e34ed1a16f.png)

This is on `gds_py:7.0` and I suspect it has to do with a change in the OSM API rather than a `osmnx` version issue.

Taggin @gboeing in case it's a temporary fix. Otherwise, we can adapt to the new structure.

**Comment by gboeing** [comment]
Can you give me a reproducible snippet for this (definition of `airbnbs_ch`)? It looks like this will be an easy fix and I can just provide you the fixed code.

**Comment by gboeing** [comment]
Just eyeballing it, it looks like it's because you're requesting `osmid` from the DataFrame's columns, but we started indexing by that instead a while back (the row labels are OSM IDs).
