### ISSUE TITLE
Six keywords or phrases for the book

### ISSUE THREAD

**Issue by sjsrey** [gdsbook/book#287]
We need 6 key words or phrases that will improve search results for the publisher. Do not repeat words in the title as they are already included (Geographic Data Science With Python).

Here is a start:

spatial analysis
spatial statistics
geocomputation
geovisualization
spatial theory and methods
open science

**Comment by ljwolf** [comment]
What went in was:
Spatial Econometrics, Geographic Information Science, Statistical Learning, Computational Geometry, Spatial Analysis, Urban Analytics
 
Obviously, missing visualization. We may want to send that along, too.
