### ISSUE TITLE
CHAPTER: Clustering & Regionalisation

### ISSUE THREAD

**Issue by darribas** [gdsbook/book#29]
Ticket to track process of "Chapter 10 - Clustering and regionalization"

**Comment by ljwolf** [comment]
#19 belongs in here.

**Comment by darribas** [comment]
Final pass stage

- [ ] Dani
- [ ] Serge
- [ ] Levi

**Comment by darribas** [comment]
Dani final pass tracker, to be edited as we go along:

Things to ensure:

- [ ] Library imports (first time inline, afterwards at the top of the chapter
- [ ] No aliases on imports (`import pandas`)
- [ ] Ensure no `XXX` for citations
- [ ] Ensure `matplotlib` RC file is picked up and figures are standard
- [ ] Remove `%matplotlib inline`
- [ ] Graphics
     - No style
     - No title (unless multi-axis titles, but not `suptitle`)
     - No axes for maps (`ax.set_axis_off()`)
- [ ] Code comments are fine if needed
- [ ] Hide/remove code cells that we want to hide (see docs [here](https://jupyterbook.org/interactive/hiding.html))
- [ ] Typesetting check
- [ ] General flow of the text

**Comment by darribas** [comment]
One note to leave here for discussion and that I think could be addressed on the "Next steps" section: we don't cover anything on measures of cluster fit (shilouettes, Kalinski-Harabaz, etc.). Should we mention at least we don't cover them for space but that they are very important?

**Comment by darribas** [comment]
@ljwolf's second last pass is over at #200, once merged, @sjsrey can give it the very final read.

**Comment by darribas** [comment]
Comments from @darribas from his second final pass:

- [ ] We're not consistent in our equation notation. Should we stick to always using $y$ or $x$ for a variable or is it OK to change and use different notation for the same thing?
- [ ] Chapter numbers are not aligned with the file name and I'm sure we've mis-referred to in several parts.
- [ ] NOTE: hiding cells do not transfer to PDF, maybe we shouldn't include _any_ hiding cell at least until the PDF/paper book is out

Other changes and edits from this pass are over at https://github.com/gdsbook/book/pull/209

**Comment by ljwolf** [comment]
Taxonomy of regionalisation paper by Juan Carlos duque 
Webpage for hdbscan
Isl 
Weber and burrow geodemographics book
