### ISSUE TITLE
New version of `xarray` does not contain `open_rasterio`

### ISSUE THREAD

**Issue by darribas** [gdsbook/book#303]
This and other minor compat issues raise errors in several chapters. We need to update the code to reflect the new API.

**Comment by sjsrey** [comment]
In [03, cell 44](https://github.com/gdsbook/book/blob/master/notebooks/03_spatial_data.ipynb):

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[44], line 1
----> 1 row2cell(t_surface.loc[0, :], surface.attrs["res"])

KeyError: 'res'
```

Looks like `res` is no longer in the `attrs` dict:

```
surface.attrs
```
gives
```
{'AREA_OR_POINT': 'Area',
 '_FillValue': -200.0,
 'scale_factor': 1.0,
 'add_offset': 0.0}
```

**Comment by darribas** [comment]
I _think_ this was fixed with the bundle of changes that went into #312, so closing for now but feel free to re-open otherwise!
