### ISSUE TITLE
CHAPTER: Choropleth Mapping

### ISSUE THREAD

**Issue by darribas** [gdsbook/book#31]
Discussion on choropleths chapter. Picks up from [GDS#5](https://github.com/sjsrey/gds/issues/5).

**Comment by darribas** [comment]
Final pass:

- [ ] Dani
- [ ] Levi
- [ ] Serge

**Comment by darribas** [comment]
Dani final pass tracker, to be edited as we go along:

Things to ensure (from #152 ):

- [x] Library imports (first time inline, afterwards at the top of the chapter
- [x] No aliases on imports (`import pandas`)
- [x] Ensure no `XXX` for citations
- [ ] Ensure `matplotlib` RC file is picked up and figures are standard
- [x] Remove `%matplotlib inline`
- [x] Graphics
     - No style
     - No title (unless multi-axis titles, but not `suptitle`)
     - No axes for maps (`ax.set_axis_off()`)
- [x] Code comments are fine if needed
- [x] Hide/remove code cells that we want to hide (see docs [here](https://jupyterbook.org/interactive/hiding.html))
- [x] Typesetting check
- [x] General flow of the text
- [ ] Ensure there is a "next step" section at the end of the chapter pointing to further references for the topic (re. #137)

**Comment by darribas** [comment]
OK my first last pass is over at https://github.com/gdsbook/book/pull/203 ready to be merged

Important to note that the chapter now is introducing at the end the use of pooled classifications, and this highlights an issue with plotting when the first class is empty. This has been filed over at: https://github.com/geopandas/geopandas/issues/2018 When fixed:

- [ ] Remove note and update the generation of pooled plots

**Comment by sjsrey** [comment]
For Further Reading:

- https://scholar.google.com/scholar_lookup?title=Thematic%20Cartography%20and%20Geographic%20Visualization&publication_year=2005&author=Slocum%2CTA&author=McMaster%2CRB&author=Kessler%2CFC&author=Howard%2CHH
- https://ij-healthgeographics.biomedcentral.com/articles/10.1186/1476-072X-8-52
- https://www.tandfonline.com/doi/abs/10.1080/02693799608902087?casa_token=_mJwhxim6j8AAAAA:iJtEd7zMtyV41H3bitx9StFC7P-h36_tWAm_VXpEHDedXAXLV-3bTjIbC-Fq-5m7EI8PCzsXd4o

**Comment by sjsrey** [comment]
> For Further Reading:
> 
>     * https://scholar.google.com/scholar_lookup?title=Thematic%20Cartography%20and%20Geographic%20Visualization&publication_year=2005&author=Slocum%2CTA&author=McMaster%2CRB&author=Kessler%2CFC&author=Howard%2CHH
> 
>     * https://ij-healthgeographics.biomedcentral.com/articles/10.1186/1476-072X-8-52
> 
>     * https://www.tandfonline.com/doi/abs/10.1080/02693799608902087?casa_token=_mJwhxim6j8AAAAA:iJtEd7zMtyV41H3bitx9StFC7P-h36_tWAm_VXpEHDedXAXLV-3bTjIbC-Fq-5m7EI8PCzsXd4o
> 
>     * https://www.esri.com/en-us/esri-press/browse/designing-better-maps-a-guide-for-gis-users

Added in #226
