### ISSUE TITLE
CHAPTER: Global Spatial Autocorrelation

### ISSUE THREAD

**Issue by darribas** [gdsbook/book#32]
Thread to discuss chapter on global autocorrelation. Picks up from [GDS#4](https://github.com/sjsrey/gds/issues/4)

**Comment by sjsrey** [comment]
I think the code in the notebook is based on an older version of pysal than is in the container:

```
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
# Generate W from the GeoDataFrame
w = weights.Distance.KNN.from_dataframe(db, k=8)
# Row-standardization
w.transform = 'R'
------------------

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-db177a29e4e5> in <module>
      1 # Generate W from the GeoDataFrame
----> 2 w = weights.Distance.KNN.from_dataframe(db, k=8)
      3 # Row-standardization
      4 w.transform = 'R'

AttributeError: module 'pysal.lib.weights' has no attribute 'Distance'
AttributeError: module 'pysal.lib.weights' has no attribute 'Distance'

make: *** [Makefile:23: latex] Error 1

(gdsbook) gds/foundry - [jupytext●] » python
Python 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysal
>>> pysal.__version__
'2.0.0'
>>> 

```

**Comment by darribas** [comment]
yes, that was part of the things that weren't quite right. I fixed this and a bunch of other general bits (e.g. data paths) on #51. I'd suggest merge that over first.

**Comment by ljwolf** [comment]
In [this](https://geographicdata.science/book/notebooks/06_spatial_autocorrelation.html#continuous-case-moran-plot-and-moran-s-i) cell, Mathias Schlaeffer writes:

> I was going through the geographicdata science book you co-authored and I have to first say a big thank you for co-authoring this book. It is a great resource and as concise as it can be, well done and thanks again.

> But I also come with a question regarding Moran's I which confused my slightly. It is described as the slope of the line fit in the Moran's scatterplot. But I suspect a small mistake went into the part creating the scatterplot. You standardize the variables Pct_Leave and Pct_Leave_Lag separately each against their respective STDDEV and AVG, where I believe the variable Pct_Leave_Lag should also be standardized against the Avg(Pct_Leave) and Stddev(Pct_Leave).

> I tested the hypothesis by recreating the variables for the scatterplot, and then deriving Moran's I from the actual slope of the line fit rather than the functionality provided in PySal. I get a slope of 0.777 which is higher than the Moran's I of 0.6454 which is cited later on. But if I use instead the described avg and stddev of the Pct_leave I get to the value of approx 0.64 as the slope.

I think that's right; we need to standardize using the mean/sd of y, not Wy?

**Comment by ljwolf** [comment]
This is ready for a second pass.

**Comment by sjsrey** [comment]
For Further Reading:

- https://escholarship.org/uc/item/3ph5k0d4 (Anselin what is special)

**Comment by sjsrey** [comment]
> In [this](https://geographicdata.science/book/notebooks/06_spatial_autocorrelation.html#continuous-case-moran-plot-and-moran-s-i) cell, Mathias Schlaeffer writes:
> 
> > I was going through the geographicdata science book you co-authored and I have to first say a big thank you for co-authoring this book. It is a great resource and as concise as it can be, well done and thanks again.
> 
> > But I also come with a question regarding Moran's I which confused my slightly. It is described as the slope of the line fit in the Moran's scatterplot. But I suspect a small mistake went into the part creating the scatterplot. You standardize the variables Pct_Leave and Pct_Leave_Lag separately each against their respective STDDEV and AVG, where I believe the variable Pct_Leave_Lag should also be standardized against the Avg(Pct_Leave) and Stddev(Pct_Leave).
> 
> > I tested the hypothesis by recreating the variables for the scatterplot, and then deriving Moran's I from the actual slope of the line fit rather than the functionality provided in PySal. I get a slope of 0.777 which is higher than the Moran's I of 0.6454 which is cited later on. But if I use instead the described avg and stddev of the Pct_leave I get to the value of approx 0.64 as the slope.
> 
> I think that's right; we need to standardize using the mean/sd of y, not Wy?

![Screenshot from 2022-01-06 09-10-51](https://user-images.githubusercontent.com/118042/148422462-6057117c-a17e-46f8-bdd3-3b9ea9cd4dba.png)

So its deviations from the mean, not also divided by the sd.

**Comment by sjsrey** [comment]
After #225 I think it is good to go.
