### ISSUE TITLE
CHAPTER: Spatial Feature Engineering

### ISSUE THREAD

**Issue by darribas** [gdsbook/book#33]
Thread to discuss development on chapter on Spatial Feature Engineering.

**Comment by ljwolf** [comment]
The original intent was to use [this chapter](https://github.com/ljwolf/geopython/blob/master/sds4-data_borrowing.ipynb) from the geopython 2017 workshop.

**Comment by darribas** [comment]
Currently being drafted over at #73. Collaboration coordinated there until a first draft is ready.

**Comment by ljwolf** [comment]
Chapter is ready to go from PR #73. We know it still needs:
1. an edit pass
2. end of chapter questions.

**Comment by ljwolf** [comment]
@tastatham noted that we're mixing up areal interpolation and dasymetric mapping (a cartographic technique, probably mean dasymetric interpolation), areal weighting (an interpolation technique), and areal interpolation (a domain of techniques) [here](https://geographicdata.science/book/notebooks/12_feature_engineering.html#area-to-area-interpolation). We'll need to make sure this gets caught and straightened out in revisions.

**Comment by darribas** [comment]
Just went over this and it's not entirely finished. There's [a section](https://geographicdata.science/book/notebooks/12_feature_engineering.html#point-interpolation-using-sklearn) that's stubbed but not completed.

In looking, it make me think, do we want to add zonal stats to this one or maybe to Ch. 2?

[Moving back to `needs review`]

**Comment by sjsrey** [comment]
I did a review and suggested a few small changes, and added four questions. Perhaps we need a few more?

**Comment by darribas** [comment]
@sjsrey first last pass was done on #201 and is merged already, the other two last passes can then take place:

- [x] Serge
- [ ] Levi
- [ ] Dani

**Comment by darribas** [comment]
Did we ever address this? @sjsrey 

> @tastatham noted that we're mixing up areal interpolation and dasymetric mapping (a cartographic technique, probably mean dasymetric interpolation), areal weighting (an interpolation technique), and areal interpolation (a domain of techniques) here. We'll need to make sure this gets caught and straightened out in revisions.

**Comment by darribas** [comment]
Edits from my final pass are over at https://github.com/gdsbook/book/pull/211

I added quite a bit of changes here and I think it'd be good to have at least one more pair of eyes laid on the final product before shipping (this and the comment from @tastatham mentioned above, which I'm not sure it's been taken into account).

**Comment by ljwolf** [comment]
Intro to deep learning book
Spatial joins reference 
interpolation (needs ref, any good conceptual overview @sjsrey @knaaptime?)
