### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by ilyankou** [gdsbook/book#65]
Hey guys,

Thank you for the wonderful book! Great start. I went through Part 1 and found a few typos, do you welcome pull requests or would you like me to mention these in the Issues?

Thank you!

**Comment by darribas** [comment]
Hi @ilyankou , thanks very much for the kind words! In general, PRs for things like typos, etc. are most welcome. For Ch.1 however I'd advice to not spend much time as it's still in its early days (although it looks like a lot of text, it's mostly from the [GDS'18](http://darribas.org/gds18/) course), so it'll hopefully change quite a bit in the coming weeks. You can have a sense of where a chapter is by looking at the [chapter issues](https://github.com/gdsbook/book/issues?q=is%3Aissue+is%3Aopen+label%3Achapter). Unless they're marked as `stable`, they'll probably change.

**Comment by ilyankou** [comment]
Got it, thanks!
