### ISSUE TITLE
Make container throws error "No module named 'jupytext'

### ISSUE THREAD

**Issue by sjsrey** [gdsbook/book#67]
```
Step 4/19 : RUN jupyter-book create testbook --demo                                                                                                                                                           
```
Throws: 
```
ModuleNotFoundError: No module named 'jupytext'
```

**Comment by darribas** [comment]
Whoops! My bad! `make container` actually builds it and that's not what we need to do. My plan is to only upgrade every six months (ie. every time there's a new PySAL/contextily/gds_env release). That way we also get the most recent `jupytext` and `jupyter-book` but, until upgrade day, the recommended way is to just pull the "official" stack. For that, this will get you there:

```
docker pull gdsbook/stack:3.0
```

Let me know if that doesn't work and sorry again for the mixup with the command...

**Comment by darribas** [comment]
Closing this as it seems resolved
